const kbDataLink = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSXS3CarlgnB2F-pE23sheC8kd9YDzxoGInuoIbiIsvJTbidOxpH7M65_l80omoRum_yxmCdk1XKImC/pub?output=csv'

const buildingMaps = [
    ['Ashworth Building', 'path193', null],
    ['Ashworth Extension', 'path194', null],
    ['Ashworth New Extension', 'path195', null],
    ['March Building', 'path196', null],
    ['John Murray Building', 'path197', null],
    ['Mary Brück Building', 'path198', null],
    ['Sanderson Building', 'path208', null],
    ['Engineering Structures Lab', 'path199', null],
    ['John Muir Building', 'path200', null],
    ['William Rankine Building', 'path201', null],
    ['Alexander Graham Bell Building', 'path202', null],
    ['Fleeming Jenkin Building', 'path203', null],
    ['Faraday Building', 'path205', null],
    ['Hudson Beare Building', 'path206', null],
    ['Hudson Beare Lecture Theatre', 'path207', null],
    ['Alrick Building', 'path204', null],
    ['Rutherford Building', 'path211', null],
    ['Waddington Building', 'path212', null],
    ['Swann Building', 'path209', null],
    ['MEP', 'path210', null],
    ['James Clerk Maxwell Building', 'path213', null],
    ['Erskine Williamson Building', 'path214', null],
    ['Grant Institute', 'path192', null],
    ['KB House', 'path191', null],
    ['Energy Centre', 'path189', null],
    ['Nucleus', 'path188', 0],
    ['The Noreen and Kenneth Murray Library', 'path190', null],
    ['Edinburgh Complex Fluids Partnership', 'path215', null],
    ['Estates Hub', 'path216', null],
    ['Peter Wilson Building', 'path217', null],
    ['Roger Land Building', 'path227', null],
    ['Christina Miller Building', 'path218', null],
    ['Joseph Black Building', 'path219', null],
    ['Arcadia Nursery', 'path220', null],
    ['Student Accommodation', 'path221', null],
    ['Murchison House', 'path222', null],
    ['Crew Annex', 'path223', null],
    ['UK Biochar Research Centre', 'path225', null],
    ['Crew Building', 'path224', null],
    ['Crew Laboratory', 'path226', null],
    ['Scottish Microelectronics Centre', 'path228', null],
    ['FloWave Ocean Energy Research Facility', 'path229', null]
]

const languages = [
    ['ar', 'Arabic'],
    ['az', 'Azerbaijani'],
    ['bg', 'Bulgarian'],
    ['bn', 'Bengali'],
    ['ca', 'Catalan'],
    ['cs', 'Czech'],
    ['da', 'Danish'],
    ['de', 'German'],
    ['el', 'Greek'],
    ['en', 'English'],
    ['eo', 'Esperanto'],
    ['es', 'Spanish'],
    ['et', 'Estonian'],
    ['eu', 'Basque'],
    ['fa', 'Persian'],
    ['fi', 'Finnish'],
    ['fr', 'French'],
    ['ga', 'Irish'],
    ['gl', 'Galician'],
    ['he', 'Hebrew'],
    ['hi', 'Hindi'],
    ['hu', 'Hungarian'],
    ['id', 'Indonesian'],
    ['it', 'Italian'],
    ['ja', 'Japanese'],
    ['ko', 'Korean'],
    ['lt', 'Lithuanian'],
    ['lv', 'Latvian'],
    ['ms', 'Malay'],
    ['nb', 'Norwegian Bokmål'],
    ['nl', 'Dutch'],
    ['pl', 'Polish'],
    ['pt', 'Portuguese'],
    ['ro', 'Romanian'],
    ['ru', 'Russian'],
    ['sk', 'Slovak'],
    ['sl', 'Slovenian'],
    ['sq', 'Albanian'],
    ['sr', 'Serbian'],
    ['sv', 'Swedish'],
    ['th', 'Thai'],
    ['tl', 'Tagalog'],
    ['tr', 'Turkish'],
    ['uk', 'Ukrainian'],
    ['ur', 'Urdu'],
    ['vi', 'Vietnamese'],
    ['zh', 'Chinese'],
    ['zt', 'Traditional Chinese']
]